language: ruby

sudo: false
cache: bundler

before_install: curl -LO 'https://search.maven.org/remotecontent?filepath=org/kill-bill/billing/killbill-profiles-killbill/0.18.8/killbill-profiles-killbill-0.18.8-jetty-console.war' && java -jar killbill-profiles-killbill-0.18.8-jetty-console.war --port 8080 --headless & sleep 25 && curl -v -X POST -u admin:password -H 'Content-Type: application/json' -H 'X-Killbill-CreatedBy: admin' -d '{"apiKey": "bob", "apiSecret": "lazar"}' "http://127.0.0.1:8080/1.0/kb/tenants"

script: 'cd kpm && bundle exec rake test:spec test:remote:spec'

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - JRUBY_OPTS='-J-Xmx1024M'

rvm:
  - jruby-1.7.20
  - jruby-20mode # latest 1.7.x
  - jruby-head

gemfile:
  - kpm/Gemfile

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  allow_failures:
    - rvm: jruby-head
    - jdk: oraclejdk8
  fast_finish: true
