inherit_from: .rubocop_todo.yml

# RuboCop 0.69.0 dropped support for 2.2
#AllCops:
#  TargetRubyVersion: 2.2
Gemspec/RequiredRubyVersion:
  Enabled: false

# Alternative?
Gemspec/RubyVersionGlobalsUsage:
  Enabled: false

Layout/DefEndAlignment:
  AutoCorrect: true

Lint/HandleExceptions:
  AllowComments: true

Metrics/LineLength:
  Max: 2000

Security/YAMLLoad:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

# Ruby 2.3+ only
Style/SafeNavigation:
  Enabled: false
