inherit_from: .rubocop_todo.yml

# Alternative?
Gemspec/RubyVersionGlobalsUsage:
  Enabled: false

Layout/DefEndAlignment:
  AutoCorrect: true

Lint/HandleExceptions:
  AllowComments: true

Metrics/LineLength:
  Max: 2000

Security/YAMLLoad:
  Enabled: false

# Ruby 2.3+ only
Style/SafeNavigation:
  Enabled: false
