---
- name: check Tomcat PID file
  stat: path="{{ catalina_base }}/tomcat.pid"
  register: tomcat_pid
  when:
    - catalina_home is defined
    - run_tomcat_handler
  listen: "restart Tomcat"

- name: stop Tomcat (with PID file)
  become: true
  become_user: "{{ tomcat_owner }}"
  environment:
    CATALINA_BASE: "{{ catalina_base }}"
    CATALINA_PID: "{{ catalina_base }}/tomcat.pid"
  command: "{{ catalina_home }}/bin/catalina.sh stop 30 -force"
  ignore_errors: True
  when:
    - catalina_home is defined
    - tomcat_pid.stat.exists == True
    - run_tomcat_handler
  listen: "restart Tomcat"

- name: stop Tomcat (without PID file)
  become: true
  become_user: "{{ tomcat_owner }}"
  environment:
    CATALINA_BASE: "{{ catalina_base }}"
  command: "{{ catalina_home }}/bin/catalina.sh stop 30 -force"
  ignore_errors: True
  when:
    - catalina_home is defined
    - tomcat_pid.stat.exists == False
    - run_tomcat_handler
  listen: "restart Tomcat"

- name: clean up Tomcat deployment files
  become: true
  become_user: "{{ tomcat_owner }}"
  file: path={{ catalina_base }}/{{ item }} state=absent
  with_items:
    - webapps/ROOT
    - work/
  when:
    - catalina_home is defined
    - run_tomcat_handler
  listen: "restart Tomcat"

- name: start Tomcat
  become: true
  become_user: "{{ tomcat_owner }}"
  environment:
    CATALINA_BASE: "{{ catalina_base }}"
    CATALINA_PID: "{{ catalina_base }}/tomcat.pid"
  command: "{{ catalina_home }}/bin/catalina.sh start"
  async: 45
  poll: 0
  when:
    - catalina_home is defined
    - not tomcat_foreground
    - run_tomcat_handler
  listen: "restart Tomcat"

- name: run Tomcat
  become: true
  become_user: "{{ tomcat_owner }}"
  environment:
    CATALINA_BASE: "{{ catalina_base }}"
    CATALINA_PID: "{{ catalina_base }}/tomcat.pid"
  command: "{{ catalina_home }}/bin/catalina.sh run"
  when:
    - catalina_home is defined
    - tomcat_foreground
    - run_tomcat_handler
  listen: "restart Tomcat"
