---
- name: fetch all migrations
  killbill_migrations:
    kpm_path: "{{ kpm_path }}"
    bundles_dir: "{{ kb_plugins_dir }}"
    kaui_web_path: "{{ catalina_base }}/webapps/ROOT.war"
    killbill_web_path: "{{ catalina_base }}/webapps/ROOT.war"
    kpm_yml: "{{ kpm_yml }}"
    gh_token: "{{ gh_token }}"
  register: migrations
  tags: migrations

- name: install Flyway
  # maven_artifact module requires xml on the host
  get_url:
    url: "{{ nexus_url }}/content/repositories/{{ nexus_repository }}/org/kill-bill/billing/killbill-util/0.18.11/killbill-util-0.18.11-flyway.jar"
    dest: "{{ kb_install_dir }}/killbill-flyway.jar"
  tags: [migrations, java_migrations]

- name: generate SQL migrations for Kill Bill and Java plugins
  command: java -jar {{ kb_install_dir }}/killbill-flyway.jar -locations=filesystem:{{ item['dir'] }} -table={{ item['table'] }} -url='{{ database_url }}' -user={{ database_user }} -password={{ database_password }} dryRunMigrate
  with_items:
    - "{{ migrations['migrations']['killbill'] }}"
    - "{{ migrations['migrations']['plugins']['java'] }}"
  when: item['dir'] is defined
  register: java_dry_run_migrations
  tags: [migrations, java_migrations]

- name: SQL migrations for Kill Bill and Java plugins
  debug: var=item.stdout_lines
  with_items: "{{ java_dry_run_migrations.results }}"
  when: item.stdout_lines is defined
  tags: [migrations, java_migrations]

- block:
  - name: wait for confirmation for Kill Bill and Java plugins
    pause: prompt='Should I run these migrations? Press return to continue. Press Ctrl+c and then "a" to abort'
    tags: [migrations, java_migrations]

  - name: run migrations for Kill Bill and Java plugins
    command: java -jar {{ kb_install_dir }}/killbill-flyway.jar -locations=filesystem:{{ item['dir'] }} -table={{ item['table'] }} -url='{{ database_url }}' -user={{ database_user }} -password={{ database_password }} migrate
    with_items:
      - "{{ migrations['migrations']['killbill'] }}"
      - "{{ migrations['migrations']['plugins']['java'] }}"
    when: item['dir'] is defined
    register: java_migrations
    tags: [migrations, java_migrations]

  - name: Flyway migrations output for Kill Bill and Java plugins
    debug: var=item.stdout_lines
    with_items: "{{ java_migrations.results }}"
    when: item.stdout_lines is defined
    tags: [migrations, java_migrations]

  when: java_dry_run_migrations.stdout.find("BEGIN;\nCOMMIT;") != -1

# TODO
# - name: generate SQL migrations for Ruby plugins
#   local_action: killbill-migration
#   with_items: "{{ migrations['migrations']['plugins']['ruby'] }}"
#   tags: [migrations, ruby_migrations]
