---
- name: fetch all migrations
  killbill_migrations:
    kpm_path: "{{ kpm_path }}"
    bundles_dir: "{{ kb_plugins_dir }}"
    kaui_web_path: "{{ catalina_base }}/webapps/ROOT.war"
    killbill_web_path: "{{ catalina_base }}/webapps/ROOT.war"
    kpm_yml: "{{ kpm_yml }}"
    gh_token: "{{ gh_token }}"
  register: migrations
  tags: migrations

- name: ensure Kill Bill install dir exists
  become: true
  file: path={{ kb_install_dir }} state=directory owner={{ tomcat_owner }} group={{ tomcat_group }}
  tags: migrations

- name: install Flyway
  # maven_artifact module requires xml on the host
  get_url:
    url: "{{ nexus_url }}/content/repositories/{{ nexus_repository }}/org/kill-bill/billing/killbill-util/{{ migrations['migrations']['from'] }}/killbill-util-{{ migrations['migrations']['from'] }}-flyway.jar"
    dest: "{{ kb_install_dir }}/killbill-flyway.jar"
  tags: migrations

- name: generate Flyway baseline tables
  command: java -jar {{ kb_install_dir }}/killbill-flyway.jar -locations=filesystem:{{ item['dir'] }} -table={{ item['table'] }} -url='{{ lookup('env','KILLBILL_DAO_URL') }}' -user={{ lookup('env','KILLBILL_DAO_USER') }} -password={{ lookup('env','KILLBILL_DAO_PASSWORD') }} baseline
  with_items:
    - "{{ migrations['migrations']['killbill'] }}"
    - "{{ migrations['migrations']['plugins']['java'] }}"
  when: item['dir'] is defined
  tags: migrations

# We verify that all migrations can be generated before attempting to run them one by one
- name: validate SQL migrations for Kill Bill and Java plugins
  command: java -jar {{ kb_install_dir }}/killbill-flyway.jar -locations=filesystem:{{ item['dir'] }} -table={{ item['table'] }} -url='{{ lookup('env','KILLBILL_DAO_URL') }}' -user={{ lookup('env','KILLBILL_DAO_USER') }} -password={{ lookup('env','KILLBILL_DAO_PASSWORD') }} dryRunMigrate
  with_items:
    - "{{ migrations['migrations']['killbill'] }}"
    - "{{ migrations['migrations']['plugins']['java'] }}"
  when: item['dir'] is defined
  register: java_dry_run_migrations
  tags: migrations

# Run core migrations
- include_tasks: migrate.yml
  loop:
    - "{{ migrations['migrations']['killbill'] }}"
  loop_control:
    loop_var: migration

# Run plugin migrations
- include_tasks: migrate.yml
  loop: "{{ migrations['migrations']['plugins']['java']|flatten(levels=1) }}"
  loop_control:
    loop_var: migration

