---
- name: ensure KPM install dir exists
  sudo: true
  file:
    path: "{{ kpm_install_dir }}"
    state: directory
  tags: kpm

- name: install KPM
  sudo: true
  unarchive:
    src: "{{ nexus_url }}/content/repositories/{{ nexus_repository }}/org/kill-bill/billing/installer/kpm/{{ kpm_version }}/kpm-{{ kpm_version }}-linux-{{ ansible_architecture }}.tar.gz"
    remote_src: True
    dest: "{{ kpm_install_dir }}"
  tags: kpm

- name: gather KPM facts
  killbill_facts:
    kpm_path: "{{ kpm_path }}"
    bundles_dir: "{{ kb_plugins_dir }}"
    kaui_web_path: "{{ catalina_base }}/webapps/ROOT.war"
    killbill_web_path: "{{ catalina_base }}/webapps/ROOT.war"
  tags: kpm

