---
- name: Deploy Tomcat
  hosts: all
  vars:
    tomcat_version: 8.5.16
    tomcat_install_dir: /opt
    tomcat_owner: tomcat
    tomcat_group: tomcat
    tomcat_home: /usr/share/tomcat
    catalina_home: /usr/share/tomcat
  become: yes
  tasks:
    - name: install Tomcat
      import_tasks: roles/tomcat/tasks/install.yml
