# Metrics stack
version: '3.2'
volumes:
  influxdb:
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - type: volume
        source: influxdb
        target: /var/lib/influxdb
      - type: bind
        source: ./influxdb/config/influxdb.conf
        target: /etc/influxdb/influxdb.conf
        read_only: true
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=killbill
      - INFLUXDB_ADMIN_PASSWORD=killbill
      - INFLUXDB_USER=killbill
      - INFLUXDB_USER_PASSWORD=killbill
      - INFLUXDB_DB=killbill
    restart: always
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_DASHBOARDS_JSON_PATH=/var/lib/grafana/dashboards
      - GF_ANALYTICS_ENABLED=false
    restart: always
