# Logging stack
version: '3.2'
volumes:
  esdata:
services:
  logstash:
    image: logstash:latest
    command: logstash -w 1 -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
    ports:
      - "1514:1514"
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
  curator:
    build: curator
  kibana:
    image: kibana:latest
    volumes:
      - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    restart: always
